kind: Template
apiVersion: v1
metadata:
  name: ${NAME}${SUFFIX}-deployment-template
  annotations:
    description: Deployment template for the von-network ledger browser.
    iconClass: icon-python
objects:
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: ${NAME}${SUFFIX}-allow-ingress
      labels:
        app: ${NAME}${SUFFIX}
        env: ${TAG_NAME}
    spec:
      description: |
        Allow traffic from routes into the ${ROLE} container(s).
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      podSelector:
        matchLabels:
          app: ${NAME}${SUFFIX}
          env: ${TAG_NAME}
      policyTypes:
        - Ingress

  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
      labels:
        app: ${NAME}${SUFFIX}
        env: ${TAG_NAME}
    stringData:
      seed: ${LEDGER_SEED}
    type: Opaque

  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
      annotations:
        description: Exposes and load balances the application pods
      labels:
        app: ${NAME}${SUFFIX}
        env: ${TAG_NAME}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          targetPort: ${{PORT}}
      selector:
        app: ${NAME}${SUFFIX}
        env: ${TAG_NAME}

  - kind: Route
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
      labels:
        app: ${NAME}${SUFFIX}
        env: ${TAG_NAME}
        certbot-managed: ${CERTBOT_MANAGED_ROUTE}
      annotations:
        haproxy.router.openshift.io/timeout: 240s
    spec:
      host: ${FQDN_HOST_NAME}
      port:
        targetPort: 8080-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${NAME}${SUFFIX}
        weight: 100

  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: ${NAME}${SUFFIX}
      annotations:
        description: Defines how to deploy the application server
      labels:
        app: ${NAME}${SUFFIX}
        env: ${TAG_NAME}
    spec:
      strategy:
        type: Recreate
      replicas: 1
      selector:
        matchLabels:
          app: ${NAME}${SUFFIX}
          env: ${TAG_NAME}
      template:
        metadata:
          name: ${NAME}${SUFFIX}
          labels:
            app: ${NAME}${SUFFIX}
            env: ${TAG_NAME}
        spec:
          containers:
            - name: ${NAME}${SUFFIX}
              image: ${IMAGE_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}
              command:
                - ./scripts/start_webserver.sh
              ports:
                - containerPort: ${{PORT}}
                  protocol: TCP
              readinessProbe:
                failureThreshold: 5
                periodSeconds: 30
                initialDelaySeconds: 3
                timeoutSeconds: 20
                httpGet:
                  path: /
                  port: 8080
              livenessProbe:
                failureThreshold: 5
                periodSeconds: 60
                initialDelaySeconds: 30
                timeoutSeconds: 20
                httpGet:
                  path: /
                  port: 8080
              env:
                - name: LEDGER_INSTANCE_NAME
                  value: ${LEDGER_INSTANCE_NAME}
                - name: LEDGER_DESCRIPTION
                  value: ${LEDGER_DESCRIPTION}
                - name: INFO_SITE_TEXT
                  value: ${INFO_SITE_TEXT}
                - name: INFO_SITE_URL
                  value: ${INFO_SITE_URL}
                - name: INDY_SCAN_TEXT
                  value: ${INDY_SCAN_TEXT}
                - name: INDY_SCAN_URL
                  value: ${INDY_SCAN_URL}
                - name: GENESIS_URL
                  value: ${GENESIS_URL}
                - name: LEDGER_SEED
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: seed
                - name: ENABLE_LEDGER_CACHE
                  value: ${ENABLE_LEDGER_CACHE}
                - name: REGISTER_NEW_DIDS
                  value: ${REGISTER_NEW_DIDS}
                - name: ENABLE_BROWSER_ROUTES
                  value: ${ENABLE_BROWSER_ROUTES}
                - name: DISPLAY_LEDGER_STATE
                  value: ${DISPLAY_LEDGER_STATE}

                - name: IP
                  value: ${IP}
                - name: PORT
                  value: ${PORT}
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}

parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the OpenShift resources associated to the server instance.
    required: true
    value: candy-monitor
  - name: SUFFIX
    displayName: Suffix
    description: A suffix applied to all of the objects in this template.
    required: false
    value: ''


  - name: IMAGE_REGISTRY
    displayName: Image Registry
    description: The name of the image registry containing the image to use for this resource.
    required: true
    value: ghcr.io/bcgov
  - name: IMAGE_NAME
    displayName: Image Name
    description: The name of the image to use for this resource.
    required: true
    value: von-network-base
  - name: IMAGE_TAG
    displayName: Image Tag
    description: The tag of the image to use for this resource.
    required: true
    value: '1.10'


  - name: FQDN_HOST_NAME
    displayName: Fully Qualified Domain Name
    description: The fully qualified domain name of the host.
    required: true
    value: dev.candy-monitor.vonx.io
  - name: CERTBOT_MANAGED_ROUTE
    displayName: Certbot Managed Route
    description: Flag indicating whether the routes certificates are managed by CertBot.
    required: true
    value: 'false'


  - name: LEDGER_INSTANCE_NAME
    displayName: Ledger Instance Name
    description: The name of the ledger instance to which the ledger monitor/browser is connected.
    required: false
    value: CANdy-Dev
  - name: LEDGER_DESCRIPTION
    displayName: Ledger Description
    description: A description for the ledger instance.
    required: false
    value: "Maintained by BC, ON, and QC"
  - name: INFO_SITE_TEXT
    displayName: Site Info Text
    description: The display text used for the `INFO_SITE_URL`. If not specified, it will default to the value set for `INFO_SITE_URL`.
    required: false
    value: dtrust-reconu
  - name: INFO_SITE_URL
    displayName: Site Info URL
    description: A URL that will be displayed in the header, and can be used to reference another external website containing details/resources on the current ledger browser instance.
    required: false
    value: https://github.com/ICCS-ISAC/dtrust-reconu/
  - name: INDY_SCAN_TEXT
    displayName: IndyScan Text
    description: The display text used for the `INDY_SCAN_URL`.
    required: false
    value: CANdyScan
  - name: INDY_SCAN_URL
    displayName: IndyScan URL
    description: The URL to the external IndyScan ledger browser instance for the network.  This will replace the links to the builtin ledger browser tools.
    required: false
    value: https://candyscan.digitaltrust.gov.bc.ca/home/CANDY_DEV/
  - name: GENESIS_URL
    displayName: Genesis Url
    description: URL for downloading a copy of the genesis file defining the ledger connection for the environment.
    required: true
    value: https://raw.githubusercontent.com/ICCS-ISAC/Candy/refs/heads/main/environments/dev/pool_transactions_genesis
  - name: LEDGER_SEED
    displayName: Ledger Seed
    description:  The ledger monitor seed to use when connecting to the ledger.
    required: true
    generate: expression
    from: "[a-zA-Z0-9_~!@#$%^&*()-=<>,.?;:|]{16}"
  - name: ENABLE_LEDGER_CACHE
    displayName: Enable Ledger Cache
    description: Flag to enable/disable the ledger cache.  It's best to disable the cache when the ledger monitor/browser is used in conjunction with IndyScan.
    required: true
    value: 'False'
  - name: REGISTER_NEW_DIDS
    displayName: Register New Dids
    description: If set to `True`, it will enable the user interface allowing new identity owners to write a DID to the ledger. It defaults to `False`.
    required: true
    value: 'False'
  - name: ENABLE_BROWSER_ROUTES
    displayName: Enable Browser Routes
    description: Flag to enable/disable the ledger browser related APIs.  It's best to disable the browser routes when the ledger monitor/browser is used in conjunction with IndyScan.
    required: true
    value: 'False'
  - name: DISPLAY_LEDGER_STATE
    displayName: Display Ledger State
    description: Flag to enable/disable the ledger state controls in the UI.
    required: true
    value: 'True'


  - name: IP
    displayName: Host IP
    description: The IP on which the server should listen.
    required: false
    value: 0.0.0.0
  - name: PORT
    displayName: Host PORT
    description: The port on which the server should listen.
    required: false
    value: "8080"


  - name: TAG_NAME
    displayName: Environment TAG name
    description: The TAG name for this environment, e.g., dev, test, prod
    required: true
    value: dev


  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
    value: 10m
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: 500m
  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
    value: 10Mi
  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
    value: 500Mi
