#!/bin/bash

set -e

SCRIPT_HOME="$( cd "$( dirname "$0" )" && pwd )"
export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
export COMPOSE_PROJECT_NAME="von"

export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)

cd "$SCRIPT_HOME"

case "$1" in
  start)
      if [ -z "$2" ]; then
        docker-compose up --force-recreate webserver node1 node2 node3 node4
      else
        if [[ $2 == *","* ]]; then
          # If arg contains comma, then it should be multiple IPS
          IPS=$2 docker-compose up --force-recreate webserver node1 node2 node3 node4
        else
          IP=$2 docker-compose up --force-recreate webserver node1 node2 node3 node4
        fi
      fi
    ;;
  cli)
      if [ -z "$2" ]; then
        docker-compose run client
      else
        docker-compose run -e IP="$2" client
      fi
    ;;
  stop)
      docker-compose stop
    ;;
  build)
      docker-compose build
    ;;
  rebuild)
      docker-compose build --no-cache
    ;;
  *)
    echo $"Usage: $0 {start|cli|stop|build|rebuild}"
esac

( cd - ) > /dev/null
