FROM bcgovimages/von-image:node-1.12-6

ENV LOG_LEVEL ${LOG_LEVEL:-info}
ENV RUST_LOG ${RUST_LOG:-warning}


ADD --chown=indy:indy indy_config.py /etc/indy/

WORKDIR $HOME
ADD --chown=indy:indy bin bin
ADD --chown=indy:indy scripts scripts

RUN mkdir -p \
    $HOME/cli-scripts \
    && chmod -R ug+rw $HOME/cli-scripts
