#!/bin/bash
set -e

SCRIPT_HOME="$( cd "$( dirname "$0" )" && pwd )"

# =================================================================================================================
# Usage:
# -----------------------------------------------------------------------------------------------------------------
usage () {
  cat <<-EOF

  Thin wrapper around cli operations.
  
  Usage: $0 [command] [options]

  Commands:

  start-client
    - Default command if no other command is specified.

  reset 
    - Delete all wallets and pools from the client container.

  init-pool <name/> <genesisUrl/>
    - Downloads the genesis file for a pool and sets it up with the specified name.
    - Allows the indy-cli to be connected to an arbitrary ledger.

  [command] [options]
    - Any command and options that can be executed by the container's shell.

  help
    - Print this usage documantation.

EOF
exit 1
}
# -----------------------------------------------------------------------------------------------------------------
# Functions:
# -----------------------------------------------------------------------------------------------------------------
toLower() {
  echo $(echo ${@} | tr '[:upper:]' '[:lower:]')
}

reset () {
  echo "Resetting pools ..."
  rm -rf ~/.indy_client/pool/*
  echo "Resetting wallets ..."
  rm -rf ~/.indy_client/wallet/*
  if [ -d ~/.indy_client/wallets ]; then
    rm -rf ~/.indy_client/wallets
  fi
}

init-pool () {
  name=${1}
  genesisUrl=${2}
  if [ -z "${name}" ] || [ -z "${genesisUrl}" ]; then
    echo "init-pool:"
    echo "Expected; init-pool <name/> <genesisUrl/>."
    exit 1
  fi

  mkdir -p .indy_client/pool/${name}
  curl ${genesisUrl} -o .indy_client/pool/${name}/${name}.txn
}
# =================================================================================================================

COMMAND=$(toLower ${1})
shift || COMMAND="start-client"

case "${COMMAND}" in
  reset)
    reset
    ;;
  init-pool)
    init-pool "$@"
    ;;
  start-client)
    ./scripts/start_client.sh
    ;;
  help)
    usage
    ;;
  *)
    eval "${COMMAND} ${@}"
    ;;
esac