#!/bin/bash

NODE_NUM="${1}"

START_PORT=9700

rm -rf .indy/*

# Nodes discover each other internally
IP1="$(getent hosts node1 | awk '{ print $1 }')"
IP2="$(getent hosts node2 | awk '{ print $1 }')"
IP3="$(getent hosts node3 | awk '{ print $1 }')"
IP4="$(getent hosts node4 | awk '{ print $1 }')"

echo generate_indy_pool_transactions \
    --nodes 4 \
    --clients 0 \
    --nodeNum $NODE_NUM \
    --ips $IP1,$IP2,$IP3,$IP4

generate_indy_pool_transactions \
    --nodes 4 \
    --clients 0 \
    --nodeNum $NODE_NUM \
    --ips "$IP1",$IP2,$IP3,$IP4

# Derive port numbers from node number (these are the ports that are generated by generate_indy_pool_transactions)
echo start_indy_node "Node"$NODE_NUM $(( $START_PORT + ( $NODE_NUM * 2 ) - 1 )) $(( $START_PORT + ( $NODE_NUM * 2 ) ))
start_indy_node "Node"$NODE_NUM $(( $START_PORT + ( $NODE_NUM * 2 ) - 1 )) $(( $START_PORT + ( $NODE_NUM * 2 ) ))
