#!/bin/bash

set -e

NODE_NUM="${1}"
START_PORT=9700

if [ ! -z $IP ]; then
    echo von_generate_transactions -i $IP -n $NODE_NUM
    von_generate_transactions -i $IP -n $NODE_NUM
else
    echo von_generate_transactions -n $NODE_NUM
    von_generate_transactions -n $NODE_NUM
fi

# echo init_indy_keys --name Node$NODE_NUM
# init_indy_keys --name Node$NODE_NUM

# Derive port numbers from node number (these are the ports that are generated by generate_indy_pool_transactions)
echo start_indy_node "Node"$NODE_NUM $(( $START_PORT + ( $NODE_NUM * 2 ) - 1 )) $(( $START_PORT + ( $NODE_NUM * 2 ) ))
start_indy_node "Node"$NODE_NUM $(( $START_PORT + ( $NODE_NUM * 2 ) - 1 )) $(( $START_PORT + ( $NODE_NUM * 2 ) ))
