#!/bin/bash

SCRIPT_HOME="$( cd "$( dirname "$0" )" && pwd )"

cd "$SCRIPT_HOME"

case "$1" in
  create)
      curl https://raw.githubusercontent.com/hyperledger/indy-sdk/master/ci/indy-pool.dockerfile > Dockerfile;
      docker build -t indy .;
      docker create -p 9701:9701 -p  9702:9702 -p 9703:9703 -p 9704:9704 -p 9705:9705 -p 9706:9706 -p 9707:9707 -p 9708:9708 --name indy indy;
    ;;
  start)
      docker start indy;
      echo "Container started. Use $0 logs to view output."
    ;;
  logs)
      docker exec -it indy bash -c 'tail -f -n 100 /var/log/indy/sandbox/*';
    ;;
  stop)
      docker start indy;
    ;;
  shell)
      docker exec -it indy bash;
    ;;
  *)
    echo $"Usage: $0 {create|start|logs|stop|shell}"
    RETVAL=1
esac

cd - > /dev/null